title = "dSplash"
base_url = "dsplash.xyz"

compile_sass = true
minify_html = true
build_search_index = true
author = "Doruk Sarp Aydın"

default_language = "en"

taxonomies = [{ name = "tags", feed = true }]

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
	{ theme = "solarized-dark", filename = "syntax-theme-dark.css" },
	{ theme = "solarized-light", filename = "syntax-theme-light.css" }
]
smart_punctuation = true
bottom_footnotes = true

[search]
index_format = "fuse_json"

[extra]
default_theme = "dark"
accent_color = "#81a1c1"
accent_color_dark = "#5e81ac"
issues_url = "https://github.com/itsdoruk/mawebsite/issues"
source_url = "https://github.com/itsdoruk/mawebsite"
show_copy_button = true
show_reading_time = true
show_share_button = true
show_backlinks = true
 toc = true
toc_inline = true
toc_ordered = true
separator = "✎"
title_separator = "-"

csp = [
	{ directive = "font-src", domains = ["'self'"] },
	{ directive = "img-src", domains = ["'self'", "https:", "data:"] },
	{ directive = "media-src", domains = ["'self'", "https:"] },
	{ directive = "script-src", domains = ["'self'"] },
	{ directive = "style-src", domains = ["'self'", "'unsafe-inline'"] },
	{ directive = "frame-src", domains = ["https://player.vimeo.com", "https://www.youtube-nocookie.com", "https://toot.community"] },
	{ directive = "connect-src", domains = ["https://toot.community"] },
	{ directive = "frame-ancestors", domains = ["'none'"] },
	{ directive = "base-uri", domains = ["'none'"] },
	{ directive = "form-action", domains = ["'none'"] }
]

[extra.nav]
show_theme_switcher = true
show_repo = true
links = [
	{ url = "@/blog/_index.md", name = "blog" },
		{ name = "my socials", menu = [
		{ url = "https://github.com/itsdoruk", name = "github" },
		{ url = "https://instagram.com/doruktheory", name = "instagram" },
		{ url = "https://vmst.io/@doruk", name = "mastodon" },
	] }
]

[extra.footer]
# Social links in the footer.
# Any URL-encoded SVG can be used as an icon.
# https://simpleicons.org is the recommended source of SVG icons.
# For URL encoding use https://yoksel.github.io/url-encoder/.
# Make sure that "external quotes" are set to "double".

show_copyright = true
show_source = true
copyright = "**Made with ❤️ by Doruk Sarp Aydın**"
